stages:
  - lint
  - build

code-lint:
  stage: lint
  tags:
    - linux
  image: python:3.12-slim
  script:
    - pip install flake8
    - flake8 . --exclude=venv

docker-build:
  stage: build
  tags:
    - linux
  image:
    name: docker:stable
  services:
   - name: docker:dind
     alias: docker

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "$GHCR_PASSWORD" | docker login --username $GHCR_USERNAME --password-stdin ghcr.io
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

    # Tagging and Pushing to GitHub Container Registry (ghcr.io)
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG ghcr.io/$GHCR_USERNAME/hass-unraid:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:latest ghcr.io/$GHCR_USERNAME/hass-unraid:latest
    - docker push ghcr.io/$GHCR_USERNAME/hass-unraid:$CI_COMMIT_TAG
    - docker push ghcr.io/$GHCR_USERNAME/hass-unraid:latest
  only:
    - tags
